выполнила  домашнее задание  HTML разметка личного проекта "Нёрдс"
htmlacademy-htmlcss/237787-nerds-31 pull request #2
Opened 2021-05-23 13:30 UTC by MakeyAlena

2021-05-23 16:36 UTC, wrgraff requested changes
Рвение — это конечно хорошо. Но почему я рекомендую не экспортировать картинки и почему так написано в задании?
Вот у тебя сейчас в большинстве картинок:
- неправильный формат
- неправильный нейминг
- часть из них лишние
А можно было сделать после лайва по графике сразу более правильно.
Пока пускай лежат, конечно, но имей ввиду, что придется их переделывать большую часть.

Страницу формы второй итерацией посмотрю, может ты что поправишь там даже после комментариев к главной.

Немного о том, как я ревью делаю.
Важные моменты, на которые нужно обязательно обратить внимание, я отмечаю смайлом ракеты 🚀. То, что в правках не нуждается, отмечено смайлом 👍. Некоторые комментарии без отметок. Если не понимаешь их или не успеваешь, то можно их оставить до следующей консультации или же вообще пропустить.
Еще прошу не нажимать на кнопку "Resolve conversation". Мне потом неудобно смотреть что я там написал. Пускай это будет моя кнопка =) Я буду ее жать если проблема исправлена. Ты можешь для себя тоже отмечать исправленный комментарий каким-то эмодзи, или писать комментарий в ответ. Как захочешь.

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +        <img src="img/cart-icon.png" width="15" height="15" alt="Иконка корзины">
Иконка у корзины несет ли в себе информацию какую-то важную?
Учитывая, что есть ссылка с текстом "Корзина".

И даже если нам нужно было поставить иконку в разметку, нужно ли ее ставить снаружи ссылки, или внутри? Как думаешь, если пользователь будет кликать по иконке, будет ли он ожидать, что ссылка сработает?

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +  </header>
А вообще, хэдер хорошо получился

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +      <h2>Цели дизайн-студия «Нёрдс»</h2>
Не сказал бы, что это цели )
Ну да ладно

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +        </li>
У тебя хорошо получается, разметь и оставшиеся 2 слайдера тоже )

Если что, в макете их можно найти [вот так](https://user-images.githubusercontent.com/37917037/119268428-9d967200-bbfb-11eb-9720-6599bfa3b13c.mov)

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +      </ul>
Еще не хватает вот этого элемента:
![изображение](https://user-images.githubusercontent.com/37917037/119268463-ca4a8980-bbfb-11eb-9442-e3d463e0bfd8.png)

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +          <img src="img/illustration-1.jpg" width="300" height="146" alt="">
Вот у тебя не получилось придумать `alt`.
Это один из верных признаков того, что картинка не контентная

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +        </li>
Оформление надо чуть подправить (это важнее, чем кажется: без хорошего оформления в хорошую компанию не возьмут никогда).

Хотя, я думаю, это просто опечатка. Весь код оформлен аккуратно у тебя

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +      <img src="img/nerds-illustration 1.png" width="360" height="208" alt="Иллюстрация логотипа " Нёрдс "">
Тоже вопрос насколько контентная картинка.

Кавычки придется использовать другие внутри кавычке атрибута `alt`.
Или вообще их удалить. Нормально читается `Иллюстрация логотипа Нёрдс` без оборачивания в кавычки названия студии.
Я вообще не люблю в кавычки ставить бренд. Бренд по сути имя. Мы же не пишем `Студентка первого курса Академии "Алёна Макей"` =)

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +          </p>
Хорошо бы, если есть тег внутри тега, всегда писать на отдельной строке.
А то там потом еще классы будут и все это станет массивнее.

Например, так:
```html
<p>
  <span>146%</span> Уровень самоотдачи
</p>
```

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +      <figure>
`figure` скорее для одной картинки подойдет. И обычно это какая-то картинка с данными или информацией, которую прям хочется подписать. Какой-нибудь график. Иллюстрация в статье. Что-то такое.

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +       <a href="blank.html"> <img src="img/logo-4 1.png" width="173" height="84" alt="Логотип" Мишка ""></a>
С кавычками и оформлением тут туже разберись

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +        <button type="submit">Напишите нам</button>
А что это вдруг тут кнопка, еще и сабмит?
Что за данные она отправит по нажатию?

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +    </section>
Тут вообще красота

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +    <button type="button">Закрыть</button>
Форму не надо размечать было, потому что это пока сложно для вас.
Но ты сделала почти идеально. Это прям хорошо.

Но забыла закрыть `section` =)

2021-05-23 16:36 UTC, wrgraff commented on index.html
> +      <p>Текст письма:</p>
Вообще, `textarea` — тоже поле ввода, ему тоже полагается `label`

2021-05-23 20:10 UTC, MakeyAlena commented on index.html
> +        <img src="img/cart-icon.png" width="15" height="15" alt="Иконка корзины">
Картинки я скорее пока для себя вставила, для наглядности мне так проще.

2021-05-23 20:10 UTC, MakeyAlena commented on index.html
> +      <h2>Цели дизайн-студия «Нёрдс»</h2>
Согласна)

2021-05-23 20:14 UTC, wrgraff commented on index.html
> +        <img src="img/cart-icon.png" width="15" height="15" alt="Иконка корзины">
Но только этой иконки не будет в разметке на самом деле )
Она тут скорее помешает своей наглядностью, так как она есть, но надо помнить, что вообще-то это декор, и надо на самом деле ее удалить.
Сложно. Я бы удалил пока. Все лишнее — долой! =)

2021-05-24 13:03 UTC, wrgraff requested changes
Хорошая работа.
По главной в принципе одна помарка осталась, но и по каталогу нашел не так уж много

2021-05-24 13:03 UTC, wrgraff commented on catalog.html
> +            </ul>
Это у нас тип сортировки. Тут все правильно.
А еще у нас есть направление, вот оно:
<img width="122" alt="изображение" src="https://user-images.githubusercontent.com/37917037/119351477-28817600-bca9-11eb-8c84-7a1d95fc04f4.png">

Его тоже нельзя упускать

2021-05-24 13:03 UTC, wrgraff commented on catalog.html
> +            <ul>
Сейчас получается, что этот список тоже попадает под заголовок "Сортировать"

2021-05-24 13:03 UTC, wrgraff commented on catalog.html
> +                    <img src="img/img-sedona 1.jpg" width="358" height="577" alt="Сайт Седона ">
Надо также разметить информацию в этой плашке:
<img width="386" alt="изображение" src="https://user-images.githubusercontent.com/37917037/119351652-62527c80-bca9-11eb-9476-97e1a6f71444.png">

Они есть в каждом элементе списка, в скрытом слое

2021-05-24 13:03 UTC, wrgraff commented on catalog.html
> +            </li>
Эти элементы списка лежат не внутри `<ul>`.
Где-то он потерялся, видимо

2021-05-24 19:31 UTC, wrgraff requested changes
По главной все (хотя там вроде в форме форматирование надо поправить, но это уж смотри).
По каталогу совсем немного.

2021-05-24 19:31 UTC, wrgraff commented on catalog.html
> +            <h3>Сортировать:</h3>
Ну, можно тогда оставить один заголовок второго уровня, а второй текст.
А то получается странненько, что у нас в сортировке еще заголовок сортировки )

Или вообще можно сделать заголовком сам текст:
`<h2>Сортировать:</h2>`

И только его оставить. Он не так уж плох в роли заголовка

2021-05-24 19:31 UTC, wrgraff commented on catalog.html
> +                        <h3>Sedona</h3>
Иногда полезно читать [ТЗ](https://up.htmlacademy.ru/htmlcss/31/project/nerds#nerds-3-10) =)

2021-05-24 19:31 UTC, wrgraff commented on catalog.html
> +                        <button type="button">9 900 ₽</button>
Такие вещи часто делаются ссылкой, чтобы сохранять функциональность при отключившемся или сломавшемся JS.
Это для магазинов критичная функциональность все-таки

2021-05-25 21:24 UTC, MakeyAlena commented on catalog.html
> +                        <h3>Sedona</h3>
Косяк

2021-05-25 23:09 UTC, wrgraff requested changes
Захвалил я тебя что ли? )))
2 поправки, и обе не туда. Ну да ничего, бывает )

2021-05-25 23:09 UTC, wrgraff commented on catalog.html
> +                        </a>
Ссылкой должен быть только текст с названием шаблона.
А кнопки вообще нельзя вкладывать в ссылки, так как это интерактивные элементы.
Можешь это проверять, кстати, на [этом замечательном сервисе](https://caninclude.glitch.me/can/include/?child=button&parent=a)

2021-05-25 23:09 UTC, wrgraff commented on catalog.html
> +                            <button type="button">9 900 ₽</button>
Имел ввиду кнопку сменить на ссылку, а не положить внутри ссылки =)

2021-05-26 09:04 UTC, wrgraff approved these changes

2021-05-26 09:04 UTC, merged