Графика всех страниц
htmlacademy-htmlcss/237787-nerds-31 pull request #3
Opened 2021-05-26 10:22 UTC by MakeyAlena

2021-05-26 19:48 UTC, wrgraff requested changes
Нужно поправить наименования некоторых картинок:
- [ ] `icon/map-marker 1.png` — пробелы в имени файла недопустимы
- [ ] `illustration/illustration-1.jpg` — эта и другие номера: не очень хорошее название, папка называется "иллюстрация" и картинки так же. Можно назвать их по применению, чтобы даже не смотря на них можно было применить нужную картинку, например "sites.png"
- [ ] `illustration/illustration-1.jpg` — для таких плоских картинок стоит использовать png. Они даже весить меньше будут, потому что png сжимает такие плоские картинки очень эффективно

А вообще неплохо )

2021-05-26 19:48 UTC, wrgraff commented on catalog.html
> +    <link rel="icon" href="img/favicon/icon.svg" type="image/svg+xml">
Тут путь указан правильно. Но если посмотреть саму папку, то она называется с большой буквы.

В названиях файлов и папок нам нужно придерживаться нижнего регистра. Дело в том, что некоторые операционные системы учитывают регистр, а некоторые нет.
Может случиться так, что работали вы в системе, что регистр не учитывает, а проект опубликован в той, что учитывает. И тогда у вас все будет работать несмотря на разные буквы, а в опубликованной версии — нет. И это будет совсем не здорово.

Поэтому разработчики условились всегда называть файлы и папки в нижнем регистре.

2021-05-26 19:48 UTC, wrgraff commented on catalog.html
> +                    <img src="img/catalog/img-sedona.jpg" width="358" height="577" alt="Сайт Седона">
Немного странно, что тут названия файлов начинаются с `img-`.
Но это не страшно )

2021-05-26 19:48 UTC, wrgraff commented on catalog.html
> +                    <img src="img/catalog/img-pink.jpg" width="358" height="578" alt="Сайт PINK">
Кроме того, это довольно важные картинки с мелкими деталями.
Можно для большей четкости выбрать png

2021-05-26 23:20 UTC, wrgraff approved these changes
Ну это к следующему заданию поправить можно )
Поторопилась как-то ты

2021-05-26 23:20 UTC, wrgraff commented on catalog.html
> +                    <img src="images/catalog/img-sedona.png" width="358" height="577" alt="Сайт Седона">
Названия **файлов** же, а не папки )

2021-05-26 23:20 UTC, merged

2021-05-27 15:26 UTC, MakeyAlena commented on catalog.html
> +                    <img src="images/catalog/img-sedona.png" width="358" height="577" alt="Сайт Седона">
я то думаю, нормальное название папки. А оказывается читать нормально надо)