Стилизация главной страницы
htmlacademy-htmlcss/237787-nerds-31 pull request #4
Opened 2021-05-30 19:20 UTC by MakeyAlena

2021-05-31 16:21 UTC, wrgraff requested changes
Хорошая работа.
В основном тут рекомендации, но по паре критериев поправки тоже есть )

2021-05-31 16:21 UTC, wrgraff commented on css/style.css
> +  --footer-grey: #444444;
Нейминг спорный с точки зрения удобства.

Одни цвета имеют абстрактное название, а другие привязаны к месту.
А что, если там понадобится цвет `#444444`, но не в футере? Ставить переменную футера не в футер, или заводить переменную с другим именем, но точно таким же цветом?

Еще смущают немного названия вроде `--basic-light` и `--basic-dark`. `basic` же может означать какой-то базовый оттенок в том числе.

Не знаю, видела или нет, я [рекомендацию давал по именованию цветов](https://t.me/mentoriumChannel/55).

В общем, я бы подумал еще над переменными

2021-05-31 16:21 UTC, wrgraff commented on css/style.css
> +h1 {
`h1` напрямую стилизовать нельзя, нам это запрещает критерий [Д25](https://up.htmlacademy.ru/htmlcss/31/criteries#d25)

2021-05-31 16:21 UTC, wrgraff commented on css/style.css
> +  font: inherit;
Обычно наследуется только семейство, чтобы перебить браузерный стиль.
Запись более точная получится (тем более, многие параметры шрифта все равно кнопкам приходится обычно переписывать, они часто отличаются в дизайне)

2021-05-31 16:21 UTC, wrgraff commented on css/style.css
> +
У тебя так хорошо получилось классы именовать.

Можно еще комментарием разделять блоки, где идут стили для разных секций.
А то количество кода возрастет, и будет проще ориентироваться с ними.

Вроде такого:

```css
.services-item-presentations:hover,
.services-item-presentations:focus {
  ...
}

/* promo */

.promo-title {
  ...
}
```

Можно и позаметнее )

2021-05-31 16:21 UTC, wrgraff commented on css/style.css
> +  border: 2px solid #d7dcde;
У нас критерий не разрешает использовать цвета не через кастомные свойства

2021-05-31 21:13 UTC, MakeyAlena commented on css/style.css
> +h1 {
уже убрала. просто это временно, он же будет скрыт, но пока делала каталог, задала класс

2021-05-31 21:33 UTC, wrgraff commented on css/style.css
> +h1 {
Хорошо, осторожнее с этим, а то бывает такое, что нет ничего более постоянного, чем временный код )

2021-06-01 19:21 UTC, wrgraff requested changes
Совсем мелочи.
Ну и про шрифты тебе сверху докинул )

2021-06-01 19:21 UTC, wrgraff commented on index.html
> +          <a class="services-item services-presentations" href="blank.html">Заказать</a>
Теперь у тебя на ссылке класс как на элементе: `services-item` =)
Вообще, это же выглядит как любая другая кнопка. Вроде как в контактах. Только эти тут цветные.

2021-06-01 19:21 UTC, wrgraff commented on css/style.css
> +  --color-white-900: #ffffff;
Шикарно.
Только обычно белый и черный без градаций ))

2021-06-01 19:21 UTC, wrgraff commented on css/style.css
> +  font-family: "Roboto", Arial, sans-serif;
Я имел ввиду использовать тоже `inherit`, но для `font-family`.
Чтобы не переписывать параметры (можно еще кастомные свойства использовать) наследование все-таки удобнее

2021-06-01 19:21 UTC, wrgraff commented on catalog.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
Слушай, подумал тут вот что.
У тебя ж так хорошо идет все...

Я не настаиваю ни в коем случае, но посмотри на [подключение шрифтов локально](https://mentorium.frontend-design.ru/articles/include-fonts/).
Думаю, ты более чем справишься с таким методом подключения. Так что смотри, может захочешь попробовать

2021-06-01 19:21 UTC, wrgraff commented on catalog.html
> +         </label>
Отступы слегка скачут здесь

2021-06-01 19:21 UTC, wrgraff commented on catalog.html
> +        <li class="sorting-item-current">
Обычно класс, который указывает на выбранный элемент, встает вторым классом к основному:

```suggestion
        <li class="sorting-item sorting-item-current">
```

Кстати, в пагинации так и сделано )

2021-06-01 19:21 UTC, wrgraff commented on css/style.css
> +.services-item .services-item h3 {
Что-то странное тут.
Класс сам в себе наверное не должен быть?
Ну и вложенность тройная это не есть хорошо

2021-06-02 22:52 UTC, wrgraff approved these changes

2021-06-02 22:52 UTC, wrgraff commented on css/style.css
> +}
Шикарно )

2021-06-02 22:52 UTC, merged