Сетки на гридах главной страницы
htmlacademy-htmlcss/237787-nerds-31 pull request #5
Opened 2021-06-04 22:56 UTC by MakeyAlena

2021-06-05 12:23 UTC, wrgraff requested changes
Записал дополнительно [ревью по сеткам](https://youtu.be/Skax4mxJy7s), чтобы разобрать некоторые нюансы. Думаю, пока с сетками работаем, буду периодически именно ролики записывать, так как текстом не все наглядно можно показать.
И отдельно записал обзор [как сделать контакты с переполнением](https://youtu.be/Ccmu3wrjY8o).

2021-06-06 21:08 UTC, MakeyAlena commented on index.html
> +      </div>
почему? у меня же сначала </div> потом  </section> ?

2021-06-07 23:58 UTC, wrgraff requested changes
Похоже на сайт становится понемногу ))

2021-06-07 23:58 UTC, wrgraff commented on css/style.css
> +    url("../fonts/roboto.woff") format("woff");
Обычно, чтобы сохранить и написание пути ровно друг под другом, и правильный шаг отступа, я пишу так:

```css
  src:
    url("../fonts/roboto.woff2") format("woff2"),
    url("../fonts/roboto.woff") format("woff");
```

2021-06-07 23:58 UTC, wrgraff commented on index.html
> +      <div class="container">
Лишний отступ есть по вложенности.
На всякий напомню (ты наверное в курсе и так), что можно выделить много-много строк и с помощью `Tab` и `Shift + Tab` менять отступ.

А то бывает упускают по неопытности, и думают надо каждую строку двигать. А это пытка конечно

2021-06-07 23:58 UTC, wrgraff commented on index.html
> +            <div class="achievement-image"></div>
Остался пустующий див.
Ровно за этим у нас теперь есть псевдоэлементы (но о них будет позже)

2021-06-07 23:58 UTC, wrgraff commented on index.html
> +      <div class="container">
А чего не смиксовала с `<section class="services">`?

2021-06-07 23:58 UTC, wrgraff commented on index.html
> +        <img class="contacts-map" src="images/map.png" width="1440px" height="416" alt="Карта проезда">
Атрибуты ширины и высоту должны быть без единиц указаны:
```suggestion
        <img class="contacts-map" src="images/map.png" width="1440" height="416" alt="Карта проезда">
```

2021-06-07 23:58 UTC, wrgraff commented on catalog.html
> +    <div class="filters-wrapper container">
Тут 2 момента:
1. В этом блоке совсем не одни только фильтры, поэтому класс не очень соответствует
2. Ты слишком упрощаешь, создавая 2 колонки с помощью оберток. Грид позволяет нам решить это без доп оберток. Он в общем то затем и пришел, поэтому давай учиться использовать всю его силу =)

2021-06-07 23:58 UTC, wrgraff commented on catalog.html
> +    <div class="filters-wrapper container">
Вот такая сетка будет! =)

| | |
| - | - |
| filter | sorting |
| filter | templates |

2021-06-07 23:58 UTC, wrgraff commented on catalog.html
> +          <ul class="catalog-list">
Сам список шаблонов тоже можно отнести к довольно крупным сеткам. Стоит его на этом этапе сделать

2021-06-07 23:58 UTC, wrgraff commented on catalog.html
> +              <a href="#">1</a>
Кстати, с активной ссылки можно убрать `href`

2021-06-07 23:58 UTC, wrgraff commented on css/style.css
> +  min-width: 100%;
Используй еще `object-fit`.
Он поможет сделать так, чтобы карта заполняла пространство масштабируясь, а не искажая пропорции

2021-06-07 23:58 UTC, wrgraff commented on css/style.css
> +.footer-social {
Хочется и тут увидеть запас по отступам между колонками (как в навигации хэдера)

2021-06-11 20:49 UTC, wrgraff approved these changes
Принимаю, конечно, но можно скорректировать отступы и метод разметки еще

2021-06-11 20:49 UTC, wrgraff commented on css/style.css
> +       url("../fonts/roboto.woff") format("woff");
А я не так написал 🙃

Ну это не критично, но все-таки не так ))

2021-06-11 20:49 UTC, wrgraff commented on css/style.css
> +  margin-right: 100px;
А почему через отступ, а не `gap`?

2021-06-11 20:49 UTC, wrgraff commented on css/style.css
> +  display: flex;
Почему флекс?
Здесь же явные 2 колонки равные. Очень удобно для гридов. И не придется элементам ширину задавать.
Да и `gap`'ы намного удобнее отступов для всего этого.

2021-06-11 20:50 UTC, merged