Сетка на флексах для главной страницы
htmlacademy-htmlcss/237787-nerds-31 pull request #6
Opened 2021-06-15 20:42 UTC by MakeyAlena

2021-06-16 20:43 UTC, wrgraff requested changes
Ну, вот наконец я нашел и к тебе в чем придраться как следует )
Я буду много просить закладываться на гибкость и универсальность, на легкость изменения параметров. Это все очень хорошая основа для того, чтобы справиться с адаптивом легче.

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  margin-top: 49px;
При чем, я бы даже задумался о том, чтобы здесь сделать ровные по вертикали размеры и вынести немного логотип наверх.
Довольно красивое решение, как по мне:
![изображение](https://user-images.githubusercontent.com/37917037/122285030-e558a280-cef6-11eb-8ebb-514eaab5677b.png)

Но немного специфическое, поэтому тут ориентируйся по себе

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  justify-content: space-between;
Грид здесь был лучше.
Стоит скорее его улучшать, чем переделывать на флекс. Например, можно обратить внимание, что меню ровно по центру расположено. Сейчас оно у тебя по сути за счет отступа у последнего элемента становится по центру. Но это хрупкий способ. Что, если попросят изменить размеры отступов? Что, если ссылка на корзину изменится в размерах (добавятся туда товары, например)?

Я бы вот отметил скорее тот факт, что сетка выглядит так, будто логотип занимает 2 колонки и корзина 2. А центральные должно забрать под себя меню:
![изображение](https://user-images.githubusercontent.com/37917037/122286709-d07d0e80-cef8-11eb-9c65-f7091f370193.png)

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  line-height: 30px;
Вспомни, что я писал про кликабельную область ссылок в [статье про отступы](https://mentorium.frontend-design.ru/articles/margin-vs-padding/):

> Кликабельную область желательно увеличить, чтобы попасть в ссылку было проще. Мы можем использовать пространство между текстом, расположив элементы вплотную или оставив небольшой зазор

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  min-height: 431px;
Часто при использовании минимальной высоты забываете ставить отступы не только с одной стороны.
Поэтому, кнопка при переполнении вообще выпадет наружу:
![изображение](https://user-images.githubusercontent.com/37917037/122287548-b8f25580-cef9-11eb-977d-771ab25be43a.png)

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +.slider-discripnion {
Класс наверное discrip**t**ion должен быть

2021-06-16 20:43 UTC, wrgraff commented on index.html
> +              <p class="slider-clause">Математически выверенный дизайн<br>для вашего сайта или мобильного приложения.</p>
Поставила брейки — и как раз зря.
Потому я и просил их не ставить, чтобы убедиться, что наша сетка не формируется с помощью брейков, и что если мы поставим текст без форматирования, то макет не развалится. А он разваливается:
![изображение](https://user-images.githubusercontent.com/37917037/122287813-08388600-cefa-11eb-8dd0-60e1fc82bf55.png)

Нужно сперва ограничить содержание, чтобы текст на картинку так далеко не залезал.
А уже потом форматировать.

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  min-height: 431px;
Кстати, кнопка вываливается, потому что она по умолчанию инлайновая

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  padding: 17px 54px 15px 54px;
Зачем такое странное решение?
У нас кнопка на макете как раз уже 240. Даже при том, что могла бы быть и меньше. Это скорее минимальная ширина, чем максимальная.
А вот отступы лучше задать для общего класса кнопки. И их не менять. Не надо создавать размер кнопки с помощью изменения отступа. Отступ лучше взять по тем кнопкам, у которых он минимален.

Если мы так сделаем, то у нас получится кнопка с небольшими отступами минимум 240 пикселей.
Если в ней будет чуть длиннее текст — он поместится в те же 240. А если сильно длиннее, то кнопка подстроится под текст. И будет аккуратнее смотреться за счет не слишком больших отступов по краям

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  padding: 17px 40px 15px 40px;
Ну и так во всех кнопках можно

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  width: 219px;
А в контактах кнопка вообще по идее имеет ширину на весь контент плашки контактов.
То есть, можно и 100% сделать спокойно:
![изображение](https://user-images.githubusercontent.com/37917037/122289555-86e1f300-cefb-11eb-8c05-b6105d729177.png)

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  padding-bottom: 32px;
Выглядит странновато:
![изображение](https://user-images.githubusercontent.com/37917037/122289656-a24cfe00-cefb-11eb-87e7-a722b26f2916.png)

2021-06-16 20:43 UTC, wrgraff commented on css/style.css
> +  flex-wrap: wrap;
Опять же: грид тут лучше подходит.
Хорошо видны 4 колонки:
![изображение](https://user-images.githubusercontent.com/37917037/122290017-01127780-cefc-11eb-8f7a-1d967fd2b4b3.png)

И внутри можно ссылкам прям размеры задать. Ширина будет определена колонкой, а высоту ограничить стоит, потому что тут не может быть переполнения: там только логотип, и логотипы должны в ряду стоять, не слишком выдвигаясь по вертикали

2021-06-17 11:08 UTC, MakeyAlena commented on css/style.css
> +  flex-wrap: wrap;
э, что-то я не поняла, у них же и так есть размеры?

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  left: 50%;
Так они не стоят по центру, потому что позиционирование считается от левого края

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  bottom: 158px;
Сейчас эти кнопки позиционируются не относительно слайда, и находятся вот тут:
![изображение](https://user-images.githubusercontent.com/37917037/122472047-b7dc2980-cfc8-11eb-90af-d854c0d381cc.png)

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  width: 88px;
Что, если у нас будет 4 слайда?
Такие элементы интерфейса обязательно должны учитывать разное количество элементов

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  z-index: 20;
Почему именно 20?

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  box-sizing: border-box;
Не нужно делать разное поведение для блоков. Мы выбираем либо один вариант, либо другой, и применяем его ко всему проекту.
Если у нас будет меняться метод подсчета размеров блока, то работать с таким проектом станет неприятно, потому что непонятно какого поведения ожидать.
Исключения бывают, но это крайне специфические случаи (на моей практике такого не было).

Вот так можно прописать поведение для всех блоков сразу:

```
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  background-color: inherit;
А фон зачем ему наследовать?

2021-06-17 21:18 UTC, wrgraff commented on css/style.css
> +  flex-wrap: wrap;
Есть, но обычно там именно фактические размеры картинки.
Например, попадется нам странный логотип 80 на 300 пикселей. И тогда размеры будут у него прописаны ровно так же (не будем же мы пересчитывать их для каждого отдельно, да и не факт, что сможем контролировать то, что с бэкенда приходит).
И нам не очень то надо, чтобы он торчал или распирал по высоте весь наш список.

2021-06-17 21:48 UTC, wrgraff requested changes
Кажется, у тебя пока хромает определение того, где и какой именно отступ стоит выбрать и за счет чего делать резерв места под декоративные элементы.

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +  margin-bottom: 80px;
Чем плох такой подход задания отступа?
Например, тем, что может понадобиться создать слайд с большим блоком текста и без кнопки. И отступ до края слайда изменится.

Вот на самом деле на практике все происходит так, что иногда кажется, что контент-менеджеры и заказчики специально выбирают тот единственный случай, который как раз способен сломать нашу верстку.
Поэтому, чем больше гибкости, тем лучше.

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +  min-width: 100%;
Можно и просто `width`.
Если минимум 100, то и будет 100

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +.services-item ::after {
Псевдоэлементы пишутся без пробела.
Когда ты пишешь с пробелом, то это псевдоэлемент для всех элементов внутри.

Вот сейчас у тебя создалось у каждого тега внутри по псевдоэлементу:
![изображение](https://user-images.githubusercontent.com/37917037/122474903-849b9980-cfcc-11eb-8c32-5c9782a01402.png)

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +  background-position: 0 0;
Он и по умолчанию 0 0.
Вообще, тут вполне бы хватило задать фон самому элементу, без всяких псевдо

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +  padding-top: 151px;
А что, если у нас изменится раскладка каким-то образом? Исчезнет или поменяется заголовок, или что-то добавится перед заголовком, например подпись какая-нибудь?
Выглядит как-то так:
![изображение](https://user-images.githubusercontent.com/37917037/122475556-8023b080-cfcd-11eb-8ab7-3501856e291c.png)

Следует действовать проще и прямолинейнее. Если у нас картинка выставлена в фоне или абсолютом через псевдо именно для `.services-item`, то и отступ, охраняющий место под картинку, должен быть в этом же элементе.

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +  background-position: 0 0;
Почему именно к заголовку, а не к блоку в целом?
Заголовок может меняться, при этом совсем независимо от этой картинки декоративной

2021-06-17 21:48 UTC, wrgraff commented on css/style.css
> +  max-height: 180px;
Всему списку не стоит ограничивать высоту. Логотипов может стать больше.
Высоту лучше определять для элементов, чтобы попав во второй ряд все смотрелось нормально.

При чем, нужно подумать еще, какой отступ должен быть у списка и какой высоты внутри будут логотипы.
Будет не очень красиво, если они удвоят высоту, создав между ними отступ больше, чем от краев списка:
![изображение](https://user-images.githubusercontent.com/37917037/122476330-ab5acf80-cfce-11eb-9b5e-4bc6ed4c36ef.png)

А вот так будет как-то уместнее:
![изображение](https://user-images.githubusercontent.com/37917037/122476371-bc0b4580-cfce-11eb-9929-bbe84f3902eb.png)

2021-06-21 15:28 UTC, wrgraff requested changes
Записал [мини-ролик с исправлением кнопок слайдера](https://youtu.be/aDNXOl0AC9U).
Для наглядности в дополнение к комментариям

2021-06-21 15:28 UTC, wrgraff commented on css/style.css
> +  right: 50%;
`right` и `left` не работают одновременно, если у элемента есть ширина

2021-06-21 15:28 UTC, wrgraff commented on css/style.css
> +  width: 88px;
Тут все еще не очень красиво получается.
Все проще (в каком-то смысле).

Убираем ширину (я комментирую, а ты удаляй) и добавляем позицинирование слева и справа одновременно. 300 — это чтобы не залезать на кнопку.
```
  right: 300px;
  left: 300px;
//  width: 88px;
```

У нас получится растянутый блок с кнопками. Чтобы они в нем стояли по центру, поменяем выравнивание:
```
  justify-content: center;
```

Сейчас они в широком контейнере и в центре блока, но слиплись. Про это дальше

2021-06-21 15:28 UTC, wrgraff commented on css/style.css
> +  margin-top: 5px;
Верхний отступ нам не очень нужен, мы же можем двигать `.slider-controls` целиком. А вот нужны отступы по краям:
![изображение](https://user-images.githubusercontent.com/37917037/122786557-1a7d4000-d2bd-11eb-8e13-61bb4fb3f31d.png)

Это избавит от слипания

2021-06-21 15:28 UTC, wrgraff commented on css/style.css
> +  bottom: 95px;
`bottom` 2 раза написан в одном классе

2021-06-25 01:19 UTC, wrgraff requested changes

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  width: 70%;
Ширину, как и позицию правой ручки, которые судя по всему изменены относительно начального состояния, лучше прописать в атрибут `style` прямо в html-коде.
А здесь какой-то базовый стиль сделать.

Почему так?
А так мы будем ближе к истине имитировать то, как эти ручки себя будут вести, потому что их положение будет прописывать JS. И он будет это делать именно с помощью атрибута.

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  font-family: "Roboto", "Arial", sans-serif;
У лейблов же наследуется шрифт абсолютно нормально

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  box-sizing: content-box;
Старайся отдельно не менять `box-sizing`. Мы либо меняем его по всему проекту, либо нет.
Кстати, если его отключить — ничего не изменится, потому что это и так значение по умолчанию.

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  color: #283136;
Цвет обязательно нужно использовать через кастомное свойство

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  font-size: inherit;
Зачем наследовать размер шрифта сверху?

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +}
Что-то они не попадают в макет совсем.
Другие цвета, размеры.

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  left: -42px;
Вот если делать именно так, то между иконкой и текстом появляется некликабельная "дырка".
А это не очень то здорово, потому что по сути это один элемент.
Так что лучше отступ под иконку сделать внутри label

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  height: 10px;
Все-таки это ссылка, и хотелось бы, чтобы кликабельная область была больше.
Рекомендации вообще лежат в районе 44 на 44 пикселя. Здесь конечно такой не получится, но надо постараться сделать настолько больше, насколько возможно

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  background-repeat: no-repeat;
`background-repeat: no-repeat;` повторяется, можно вынести его в общий класс

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  grid-template-columns: 360px 360px;
Пришлось на пиксели переписать, потому что родительская сетка кривовато работает.
Стоит оставить 1fr, но переписать сетку так, чтобы эти 2 колонки попадали в нужный размер благодаря правильному размеру родительской сетки

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +.catalog-item:focus {
По стайлгайду тень при наведении появляется только у картинки, под плашкой ее нет

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +  filter: drop-shadow(0px 6px 15px rgba(0, 0, 0, 0.25));
Не стоит копировать такое свойство из Фигмы.
Фигма глупая, потому что `filter` очень прожорливое в плане ресурсов свойство.
Оно умеет строить тень от прозрачных картинок и сложных форм, но нам это не нужно, и мы можем обойтись более производительным `box-shadow`

2021-06-25 01:19 UTC, wrgraff commented on css/style.css
> +.catalog-discription {
Даже если в макете явно не указано, стоит предусмотреть внутренний отступ для плашки, чтобы текст не выглядел слишком широким и не приближался так близко к краям:
![изображение](https://user-images.githubusercontent.com/37917037/123354460-5d187400-d56c-11eb-84ef-13635dbaeb59.png)

2021-07-02 18:07 UTC, wrgraff commented on css/style.css
> +  top: 40px;
Чуть надежнее будет позиционирование от `bottom`, так как если вдруг ссылка станет двустрочной, то высота изменится, но положение полоски это не затронет

2021-07-02 18:07 UTC, wrgraff commented on css/style.css
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
Откуда там тень? В макете ее нет

2021-07-02 18:07 UTC, wrgraff commented on css/style.css
>    background-image: url("../images/icon/shape.svg");
Во-первых, плохое название файла.
`shape.svg` — что это значит? Файл называется "форма". Как мне сделать вывод о том, что это галочка?

Потом, у тебя не получится на этом макете сделать так, чтобы чекбокс выглядел разорванным.
Тебе придется для не отмеченного элемента грузить картинку без галочки, а для отмеченного — картинку с галочкой и квадратом.

2021-07-02 18:07 UTC, wrgraff commented on css/style.css
> +  font-size: inherit;
?

2021-07-02 18:09 UTC, wrgraff requested changes
Постарайся сделать только исправления, не внедряя новые вещи.
Чтобы можно было принять ДЗ и закрыть пул-реквест

2021-07-02 18:45 UTC, MakeyAlena commented on css/style.css
>    background-image: url("../images/icon/shape.svg");
не нашла, где ответить.

 border-radius: 5px;
  background: #f1f1f1;
  font-family: inherit;
  font-size: inherit;

нет, у меня такого. я не нашла.

2021-07-03 12:09 UTC, wrgraff commented on css/style.css
>    background-image: url("../images/icon/shape.svg");
Целиком нет, а наследование размера шрифта тут (смотри по номерам строк):

![изображение](https://user-images.githubusercontent.com/37917037/124353693-af166500-dc10-11eb-8b5d-b0b92666daf8.png)

2021-07-03 12:10 UTC, wrgraff commented on css/style.css
>    background-image: url("../images/icon/shape.svg");
Остальное уже изменилось, а эта строка осталась

2021-07-03 12:10 UTC, wrgraff approved these changes

2021-07-03 12:10 UTC, merged