декоративные элементы на страницах
htmlacademy-htmlcss/237787-nerds-31 pull request #7
Opened 2021-07-03 21:18 UTC by MakeyAlena

2021-07-03 22:47 UTC, wrgraff requested changes

2021-07-03 22:47 UTC, wrgraff commented on catalog.html
> +
А это что такое?

2021-07-03 22:47 UTC, wrgraff commented on css/style.css
> +.login-form input[type="text"]:hover,
А зачем вообще указывать тип?
Другие поля будут выглядеть аналогично, почему бы не оставить просто инпут?

2021-07-03 22:47 UTC, wrgraff commented on css/style.css
> +}
Так у тебя красным будут подсвечиваться поля еще до взаимодействия с ними.
Чтобы была правильная логика и поле подсвечивалось только после взаимодействия, можно было бы использовать `:user-invalid`, но у него пока плохая поддержка.

Поэтому логично будет просто подготовить класс, который будет подключаться с помощью js.
Прописать для него стили, проверить работают ли и не использовать их по умолчанию.

2021-07-03 22:47 UTC, wrgraff commented on index.html
>      <form class="login-form" action="https://echo.htmlacademy.ru" method="post">
А почему это `login-form`?
Это же форма связи, а не авторизация

2021-07-04 10:03 UTC, MakeyAlena commented on catalog.html
> +
это я удалю потом, это что  ссылки каждый раз не прыгали)

2021-07-04 20:07 UTC, wrgraff commented on catalog.html
> +
Ох )

2021-07-04 20:10 UTC, wrgraff requested changes

2021-07-04 20:10 UTC, wrgraff commented on css/style.css
> +.form-write-us input:hover,
Получилось 2 раза просто инпут )
Здесь и в фокусе

2021-07-04 20:10 UTC, wrgraff commented on css/style.css
> +.form-write-us input[type="text"] {
А тут не получается убрать тип из селектора?

2021-07-04 20:10 UTC, wrgraff commented on css/style.css
> +.form-write-us input:invalid {
Тут не поправила, лучше сделать класс (можно в купе с `:user-invalid`

2021-07-05 20:51 UTC, wrgraff requested changes
Исключительно из-за невнимательности получается опять в доработку отправляю

2021-07-05 20:51 UTC, wrgraff commented on css/style.css
> +.form-write-us input {
Ну надо же как-то внимательнее... Вот как мне принять работу, когда в ней написано 2 одинаковых селектора через запятую?

2021-07-05 20:51 UTC, wrgraff commented on css/style.css
> +.form-invalid input:invalid {
И тут селекторы одинаковые

2021-07-05 21:49 UTC, MakeyAlena commented on css/style.css
> +.form-write-us input {
Это, ты как-то очень корректно выразился, я бы конечно, по-другому сказала. Причём что именно на это и смотрела...

2021-07-05 22:04 UTC, wrgraff commented on css/style.css
> +.form-write-us input {
Ну я вслух поргуался, а потом написал =)

2021-07-05 22:06 UTC, wrgraff approved these changes
Так, я вижу тут какие-то отступы еще изменились.
Под ПП подгоняешь? Я пока не буду смотреть, на допуске перед защитой все равно ПП проверять надо будет

2021-07-05 22:06 UTC, merged